rerun:
  distances: false
  dihedrals: false
  new_descriptors: false
data_generation:
  schrodinger_path: /opt/schrodinger/suites2024-3
  main_dir: /Users/zaansaeed/Desktop/PermeabilityDataset
  smiles_input_file: all_peptides.smi
  names_input_file: all_ids.txt
  target_input_file: all_permeabilities.txt
  conf_search_settings:
    wait_time_for_conf_search: 120
    CONFSEARCH_METHOD: MCMM
    FORCE_FIELD: OPLS_2005
    SOLVENT: None
    DIELECTRIC_CONSTANT: 1.0
    CHARGES_FROM: Force field
    CUTOFF: None
    MINI_METHOD: PRCG
    MAXIMUM_ITERATIONS: 2500
    CONVERGE_ON: Gradient
    CONVERGENCE_THRESHOLD: 0.05
    OUTCONFS_PER_SEARCH: 10000
    CONFSEARCH_STEPS: 1000
    CONFSEARCH_STEPS_PER_ROTATABLE: 100
    ENERGY_WINDOW: 104.6
    CONFSEARCH_TORSION_SAMPLING: Intermediate
  number_of_residues: 6
machine_learning:
  target_name: target
  model_name: RandomForestRegressor
  n_iter: 5
  features_to_train_on:
  - side_chain_descriptors
  save_model: true
  models:
  - RandomForestRegressor
  - ElasticNet
  - SVR
